"""another migration

Revision ID: 081252d1326e
Revises: 30a9844a593e
Create Date: 2018-05-31 08:27:45.565195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081252d1326e'
down_revision = '30a9844a593e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer', sa.String(), nullable=True))
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'reviewer')
    # ### end Alembic commands ###
